name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

  testing:
    runs-on: ubuntu-latest
    env:
      retarus_fax_username: ${{secrets.RETARUS_FAX_USERNAME}}
      retarus_fax_password: ${{secrets.RETARUS_FAX_PASSWORD}}
      retarus_cuno: ${{secrets.RETARUS_CUNO}}
      retarus_sms_username: ${{secrets.RETARUS_SMS_USERNAME}}
      retarus_sms_password: ${{secrets.RETARUS_SMS_PASSWORD}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - run: go test ./...
